# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ErosionMap
                                 A QGIS plugin
 Tool to create coastal change heatmaps from point clouds
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-24
        copyright            : (C) 2024 by Noa David
        email                : noadavid@hotmail.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Noa David'
__date__ = '2024-10-24'
__copyright__ = '(C) 2024 by Noa David'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ErosionMap class from file ErosionMap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .erosion_map import ErosionMapPlugin
    return ErosionMapPlugin(iface)
